### ISSUE TITLE
[GS] expression command could give better return values

### ISSUE THREAD

**Issue by lesquoyb** [gama-platform/gama#620]
**Describe the bug**
Currently the expression command always return a string value, but the json format used could support int, float, bool and complex values (dictionaries).

**To Reproduce**
1. Run any gama model
2. in a client ask for the `color` value of the simulation
4. See something like `'color[transparent]'`

**Expected behavior**
int, float and bool values could be unpacked and do not need to be wrapped into a string, complex objects could be serialized into json objects. For example a color would be something like this:
```yaml
{
'gaml_type': 'rgb', 
'red': 255, 
'green': 0, 
'blue': 0, 
'alpha': 255
}
```
